# Copyright FUJITSU LIMITED 2018.

- name: git clone plugin sample repo
  git:
    repo: https://github.com/personium/personium-plugin-sample.git
    dest: /tmp/personium-plugin-sample
    version: "{{ personium_plugin_sample_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: build plugin sample
    command: /opt/apache-maven-3.3.9/bin/mvn package -DskipTests
    args:
      chdir: /tmp/personium-plugin-sample
    environment:
      JAVA_HOME: /opt/jdk
    register: result
    until: result.stdout.find('BUILD SUCCESS') != -1
    retries: 3
    delay: 20

  - name: deploy plugin sample
    command: cp /tmp/personium-plugin-sample/target/personium-plugin-sample.jar /personium/personium-core/plugins/personium-plugin-sample.jar
  when: gitclone.changed

- name: git clone ex httpclient repo
  git:
    repo: https://github.com/personium/personium-ex-httpclient.git
    dest: /tmp/personium-ex-httpclient
    version: "{{ personium_ex_httpclient_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: build ex httpclient
    command: /opt/apache-maven-3.3.9/bin/mvn package -DskipTests
    args:
      chdir: /tmp/personium-ex-httpclient
    environment:
      JAVA_HOME: /opt/jdk
    register: result
    until: result.stdout.find('BUILD SUCCESS') != -1
    retries: 3
    delay: 20

  - name: deploy ex httpclient
    command: cp /tmp/personium-ex-httpclient/target/personium-ex-httpclient.jar /personium/personium-engine/extensions/personium-ex-httpclient.jar
  when: gitclone.changed

- name: git clone ex mailsender repo
  git:
    repo: https://github.com/personium/personium-ex-mailsender.git
    dest: /tmp/personium-ex-mailsender
    version: "{{ personium_ex_mailsender_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: build ex mailsender
    command: /opt/apache-maven-3.3.9/bin/mvn package -DskipTests
    args:
      chdir: /tmp/personium-ex-mailsender
    environment:
      JAVA_HOME: /opt/jdk
    register: result
    until: result.stdout.find('BUILD SUCCESS') != -1
    retries: 3
    delay: 20

  - name: deploy ex mailsender
    command: cp /tmp/personium-ex-mailsender/target/personium-ex-mailsender.jar /personium/personium-engine/extensions/personium-ex-mailsender.jar
  when: gitclone.changed

- name: git clone ex slack messanger repo
  git:
    repo: https://github.com/personium/personium-ex-slack-messenger.git
    dest: /tmp/personium-ex-slack-messenger
    version: "{{ personium_ex_slack_messenger_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: build ex slack messanger
    command: /opt/apache-maven-3.3.9/bin/mvn package -DskipTests
    args:
      chdir: /tmp/personium-ex-slack-messenger
    environment:
      JAVA_HOME: /opt/jdk
    register: result
    until: result.stdout.find('BUILD SUCCESS') != -1
    retries: 3
    delay: 20

  - name: deploy ex slack messanger
    command: cp /tmp/personium-ex-slack-messenger/target/personium-ex-slack.jar /personium/personium-engine/extensions/personium-ex-slack.jar
  when: gitclone.changed

- name: git clone ex ew services repo
  git:
    repo: https://github.com/personium/personium-ex-ew-services.git
    dest: /tmp/personium-ex-ew-services
    version: "{{ personium_ex_ew_services_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: build ex ew services
    command: /opt/apache-maven-3.3.9/bin/mvn package -DskipTests
    args:
      chdir: /tmp/personium-ex-ew-services
    environment:
      JAVA_HOME: /opt/jdk
    register: result
    until: result.stdout.find('BUILD SUCCESS') != -1
    retries: 3
    delay: 20

  - name: deploy ex ew services
    command: cp /tmp/personium-ex-ew-services/target/personium-ex-ew-services.jar /personium/personium-engine/extensions/personium-ex-ew-services.jar
  when: gitclone.changed

# Install Unit Manager Application

- name: git clone app unit manager repo
  git:
    repo: https://github.com/personium/app-uc-unit-manager.git
    dest: /tmp/app-uc-unit-manager
    version: "{{ personium_app_unit_manager_version }}"
    depth: 1
    force: yes
  register: gitclone

- block:
  - name: Setup Unit-Manager login.js
    replace: 
      dest: /tmp/app-uc-unit-manager/src/html/js/login.js
      regexp: "let appUnitFQDN = 'demo.personium.io';"
      replace: "let appUnitFQDN = 'localhost:1210';"
      backup: yes

  - name: Setup Unit-Manager login.js
    replace:
      dest: /tmp/app-uc-unit-manager/src/html/js/login.js
      regexp: "managerUrl = 'https://'+appUnitFQDN+'/app-uc-unit-manager/';"
      replace: "managerUrl = 'https://'+appUnitFQDN+'/Unit-Manager/';"

  - name: Setup Unit-Manager login.js
    replace:
      dest: /tmp/app-uc-unit-manager/src/html/js/login.js
      regexp: "managerUrl = 'https://app-uc-unit-manager.'+appUnitFQDN+'/';"
      replace: "managerUrl = 'https://'+appUnitFQDN+'/Unit-Manager/';"
  
  - name: Setup Unit-Manager login.js
    replace:
      dest: /tmp/app-uc-unit-manager/src/html/js/login.js
      regexp: "managerUrl = 'https://'+appUnitFQDN+'/app-uc-unit-manager/';"
      replace: "managerUrl = 'https://'+appUnitFQDN+'/Unit-Manager/';"

  - name: Setup Unit-Manager default Unit URL
    replace:
      dest: /tmp/app-uc-unit-manager/src/html/login.html
      regexp: '<input type="text" autocomplete="off" placeholder="Login URL (with ending slash)" name="loginUrl" id="loginUrl" class="txtUnitUrl">'
      replace: '<input type="text" autocomplete="off" placeholder="Login URL (with ending slash)" name="loginUrl" id="loginUrl" class="txtUnitUrl" value="https://localhost:1210/unitadmin/">'

  - name: Create /opt/nginx/html/Unit-Manager
    file: state=directory path=/opt/nginx/html/Unit-Manager owner=root group=root mode=0755

  - name: deploy app unit manager repo
    copy: src=/tmp/app-uc-unit-manager/src/html/ dest=/opt/nginx/html/Unit-Manager/ owner=root group=root mode=755
  when: gitclone.changed

- name: restart tomcat
  systemd: name=tomcat state=restarted

- name: restart nginx
  systemd: name=nginx state=restarted